#!/usr/bin/env bash

# $1 = root directory, $2 = remote, $3 = branch names, $4 = ff only, $5 = regex 
# set -e

# constants
get_repository_name_regex='^.+\/\(.*\)\.git$'
get_stash_regex='^\([^:]\+\).*'

# variables
root_directory="${1:-.}"
remote="${2:-origin}"
IFS=',' read -ra branches <<< "${3:-master}" 
ff_only="${4:-true}"
repository_name_regex="${5:-.*}"

# verify variables
# echo "${root_directory}"
# echo "${remote}"
# echo "${branches[@]}"
# echo "${ff_only}"

# functions
elementIn()
{
	local toSearch element
	toSearch="${1}"
  	shift
  	for element; do [[ "$element" == "$toSearch" ]] && return 0; done
  	return 1
}

# script
pushd ${root_directory}
echo "changed to directory ${root_directory}"

for folder in */
do
	pushd "${folder}"
	echo "changed to directory $folder"

	IFS='' read -ra existing_remotes <<< $(git remote)

	echo "existing remotes: ${existing_remotes[@]}"

	if ! elementIn "${remote}" "${existing_remotes[@]}"
	then
		echo "${remote} does not exist!"
		echo "Skipping this repository."
		popd
		continue
	fi

	remote_url=$(git remote get-url "${remote}")
	repository_name=$(echo "${remote_url}" | sed 's/'"${get_repository_name_regex}"'/\1/')

	echo "remote url: ${remote_url}"
	echo "repository name: ${repository_name}"

	#if [[ ${repository_name} == ${remote_url} ]]
	#then
	#	echo "Skipping this repository since $remote_url does not look like a valid git remote url"
	#	popd
	#	continue
	#fi

	shopt -s nocasematch

	if [[ ! ${repository_name} =~ ${repository_name_regex} ]]
	then
		echo "Skipping ${repository_name} since it does not match the given regex ${repository_name_regex}"
		popd
		continue
	fi

	shopt -u nocasematch

	echo 'fetching new content for '"${remote_url}"
	git fetch --tags --prune "${remote_url}" "${branches[@]}"

	if [[ ! $? -eq 0 ]]
	then
		echo "One or multiple branches of ${branches[@]} were not found on the remote."
		echo "Skipping this repository."
		popd
		continue
	fi

	initialBranch="$(git rev-parse --abbrev-ref HEAD)"
	stashed=false

	for branch in "${branches[@]}"
	do
		echo "checking out branch $branch"
		git checkout "${branch}"

		if [[ ! $? -eq 0 ]]
		then
			stashMessage="$(date +"%Y-%m-%d_%H-%M-%S"): uncommitted changes on branch $(git rev-parse --abbrev-ref HEAD)"
			git stash push -m "${stashMessage}"
			stashed=true
			git checkout "${branch}"
		fi

		if [[ "${ff_only}" = true ]]
		then
			echo "fast foward merging with ${remote}/${branch}"
			git merge --ff-only "${remote}"/"${branch}"
		else
			echo "merging with ${remote}/${branch}"
			git merge "${remote}"/"${branch}"
		fi
	done

	git checkout "${initialBranch}"
	if $stashed
	then
		# use the stash where message matches the stashMessage instead
		ourStash=$(git stash list | grep "${stashMessage}" | sed 's/'"${get_stash_regex}"'/\1/')
		echo "Stash containing uncommitted work tree changes: $ourStash"
		git stash pop "${ourStash}"
	fi

	popd
done
